config/routes.rb
Rails.application.routes.draw do


root 'pages#home'

get 'pages/about', to: 'pages#about'

resources :articles


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article <  ActiveRecord::Base
	validates :title, presence: true, length:{minimum:3, maximum:50}

	validates :description, presence:true, length:{minimum: 10, maximum:300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]

	def index
		@article = Article.all
	end

	def new
		@article = Article.new

	end

	def edit

		
	end

	def create

		
		@article = Article.new(article_params)
		
		if @article.save
			flash[:notice] = "Article was succesfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def show

						
	end

	def destroy

		
		@article.destroy
		flash[:notice] = "Article was succesfully deleted"
		redirect_to articles_path
	end

	def update
		if @article.update(article_params)
			flash[:notice] = "Article was succesfully edited"
			redirect_to article_path(@article)
		else
			render 'edit'
		end

	end

	private

	def set_article	
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<ul>
	<%@article.errors.full_messages.each do |msg| %>
	<li><%= msg %> </li>
</ul>
	<%end%>
<%end%>

<%= form_for @article do |f| %>
<p>
	<%= f.label :title %><br/>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :description %><br/>
	<%= f.text_area :description%>
</p>
<p>

<%= f.submit%>

</p>

<% end %>

<%= link_to "Back to articles listing", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing articles</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<p><%= link_to "Create new article", new_article_path %></p>

<table>
   <tr>
 	<th>Title</th>
 	<th>Description</th>
   </tr>
   <% @article.each do |article| %>
   <tr>
     <td><%= article.title %></td>
     <td><%= article.description %></td>
     <td><%= link_to "Edit", edit_article_path(article) %></td>
     <td><%= link_to "Show", article_path(article) %></td>
     <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %> </td>
    </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>Title: <%= @article.title %></p>

<p>Description: <%= @article.description%> </p>

<%= link_to "Edit this article", edit_article_path(@article) %>
<br>
<%= link_to "Back to articles listing", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alphablog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>
	body {
    /* Typography Declarations */
    color: #222222;
    font-size: 1em;
    font-family: "Open Sans", "Helvetica Neue", sans-serif;
}

.content-footer,
.masthead-heading,
.masthead-intro {
  text-align: center;
}

.masthead {
  padding: 6em 0;
  background-image: url('https://i.imgur.com/yGmrlyg.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  border-top: solid 1em #FFCF33;
}

.masthead-intro {
    /* Layout Declarations */
    margin-bottom: 0.1em;
    /* Typography Declarations */
    font-family: "Gentium Book Basic", Georgia, serif;
    font-size: 2em;
}

.masthead-heading {
    /* Layout Declarations */
    color: #F1C863;
    margin-top: -0.2em;
    /* Typography Declarations */
    font-family: "Open Sans", "Helvetica Neue", sans-serif;
    font-weight: bold;
    font-size: 6em;
    letter-spacing: -0.02em;
    text-transform: uppercase;
}

.introduction-section,
.location-section,
.questions-section {
    max-width: 38em;
    margin-left: auto;
    margin-right: auto;
    margin-top: 2em;
}

.introduction-section > p,
.location-section > p,
.questions-section,
.content-footer > p {
    /* Typography Declarations */
    font-weight: 300;
    letter-spacing: 0.05em;
}

.questions-section > h2 {
    font-family: "Gentium Book Basic", Georgia, serif;
    font-size: 1.2em;
    font-weight: bold;
    /* Layout */
    margin: 2em 0 1em 0;
}

section > h1 {
    margin-top: 2em;
}

.content-footer,
.masthead-heading,
.masthead-intro {
  text-align: center;
}

.masthead {
  padding: 6em 0;
  background-image: url('https://i.imgur.com/yGmrlyg.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  border-top: solid 1em #FFCF33;
}

.masthead-intro {
  margin-bottom: 0.1em;
  font-family: "Gentium Book Basic", Georgia, serif;
    font-size: 2em;
}

.masthead-heading {
  margin-top: -0.2em;
  font-family: "Open Sans", "Helvetica Neue", sans-serif;
  font-weight: bold;
  font-size: 6em;
  letter-spacing: -0.02em;
  text-transform: uppercase;
}
.introduction > p,
.location > p,
.content-footer > p {
    /* Typography Declarations */
    font-weight: 300;
    letter-spacing: 0.05em;
}
h2 {
    /* Typography Declarations */
    font-family: "Gentium Book Basic", Georgia, serif;
    font-size: 1.2em;
    font-weight: bold;
}

.introduction-section,
.location-section,
.questions-section {
    max-width: 38em;
    margin-left: auto;
    margin-right: auto;
    margin-top: 2em;
}
.content-footer {
  margin: 50px 0;
  padding: 20px 0;
  text-align: center;
  background-color: #73A8C2;
  text-decoration: none;
}
.social > li {
  display: inline-block;
  margin: 0 5px;
}
.content-footer > p {
  color: #F7EDE1;
}
a {
    font-weight: bold;
    text-decoration: none;
    color: #F1C863;
}
  
@media only screen and (max-width: 500px) {
    .masthead {
        padding: 3em 0;
    }
    .masthead-heading {
        font-size: 3em;
    }
    .content-footer {
        padding: 2em 2.5em;
  }
}
	</style>
	<title></title>
</head>
<body>
<<header class='masthead'>
  <p class='masthead-intro'>Hi I'm</p>
  <h1 class='masthead-heading'><%= link_to 'Peter', root_home_path %></h1>
</header>
<section class="introduction-section">
    <h1>Introduction</h1>
    <p>I am a construction business owner, part time marketer, and soon to be web developer.</p>
    <p>I love the internet, technology, and building beautiful things.</p>
</section>
<section class="location-section">
    <h1>Where I'm From</h1>
    <p>I'm originally from Washington D.C. </p>
</section>
<section class="questions-section">
    <h1>More About Me</h1>
    <h2>What are your favorite hobbies?</h2>
    <p>My favorite hobby is building things on the internet like ecommerce sites and email marketing campaigns.</p>
    <h2>What's your dream job?</h2>
    <p>My dream job is similar to my current job except I would like to be building software instead of buildings.</p>
    <h2>Where do you live?</h2>
    <p>I live on a rural acreage, but I'm close to Ottawa and Montreal.</p>
    <h2>Why do you want to be a web developer?</h2>
    <p>Because programming is awesome and programming for the internet is even more awesome.</p>
</section>

<footer class="content-footer">
    <p>Say hi to me on these social networks:</p>
    <ul class="social">
        <li><a class="css-is-deranged" href="_INSERT_GITHUB_URL_HERE_">GitHub</a></li>
        <li><a class="css-is-deranged" href="_INSERT_TWITTER_URL_HERE_">Twitter</a></li>
        <li><a class="css-is-deranged" href="_INSERT_GOOGLE+_URL_HERE_">Google+</a></li>
    </ul>
  
</footer>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>
		.container{
			display: grid;
			grid-template-columns: 30% 40% 20%;
		}

		.items{

			height: 150px;
 			width: auto;
 			outline: 2px solid black;
  			background-color: powderblue;
  			grid-column-start: 1;
  			grid-column-end: end;
  			text-align: center;
  			font-size: 2em;

		}

		.nextItems{

			outline: 2px solid black;
			height: auto;
 			width: auto;
 			grid-column-start: 1;
  			grid-column-end: 3;
  			margin-top: 10px;
  			margin-bottom: 10px;
		}

		.sideItems{
			outline: 2px solid black;
			height: auto;
 			width: auto;
 			grid-column-start: 3;
  			grid-column-end: end;
  			color: red;
  			text-align: center;
  	
		}

		 img { 
                width: 100%; 
                height: 75%; 
                object-fit: contain; 
            } 

	</style>

	<title></title>
</head>
<body>
<div class = "container">
<div class = 'items'>Alpha Blog - Udemy Rails Project <%= image_tag 'thinkinghomer.png' %></div>
<div class = 'nextItems' >Some of things that I am still tackling is approval, perfectionism, and trying to be friends with everyone.  I certainly value good friendships and being able to work with everyone in respectful way.  

There is always someone negative around me who seem to look only at the negative qualities.  I have to constantly remind myself that no is completely negative and no is completely positive.  Everyone in the work place has their good qualities and bad qualities.  </div>
<div class = "sideItems"><%= link_to 'About Me', pages_about_path %></div>
<div></div>
<div class = "nextItems"><b>What do you think your main purpose in life?</b>



When I think about my main purpose in life is the self development or trying to the best human you can be.  Whether that come from physical, mental, emotional, and financial aspects of life.  



I think my parents always were trying hard to be best but at times were frustrated with each other in terms of what it really meant.  I don't think they were ever truly happy with that what they accomplished and it rubbed off on us children.  </div>
<div class = "sideItems"><a>Buy My book about Being Alpha</a></div>
<div></div>
<div class = "nextItems"><b>What would you like to achieve most?</b>



I really would like to achieve a sense of financial freedom.  I would love to life life on my own terms make my own money, live where I want to live, do what I want to do everyday.  If I want to play golf everyday so be it.  If I want to go to the gym and play basketball I can.  I don't want to be tied to any job,  work.  I want to create more freedom in my life.  

</div>
<div class = "sideItems"><%= link_to "Learn More Articles", articles_path %></div>


</div>


</body>
<script type="text/javascript"></script>
</html>